name = "OnlineStatsBase"
uuid = "925886fa-5bf2-5e8e-b522-a9147a512338"
version = "0.13.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LearnBase = "7f8f8fb0-2700-5f03-b4bd-41f8cfc144b6"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test"]
